(() => {
(()=>{var u=(e,t)=>()=>(t||e((t={exports:{}}).exports,t),t.exports);var h=u((b,E)=>{if(!window?.location?.href||!window.location.href.startsWith("https://my.ucdavis.edu/schedulebuilder/"))throw alert("This bookmarklet only works on the UCD Schedule Builder page (https://my.ucdavis.edu/schedulebuilder/)."),new Error("Not on UCD Schedule Builder page");var $=(()=>{let e=[],t=schedule.currSched.get(),r=CourseDetails[[Object.keys(CourseDetails)[0]]].COURSE_MATERIALS_TERM;for(let i in t)if(t[i].STORED_REGISTRATION_STATUS==="Registered"){let s=CourseDetails[i];e.push({title:`${s.SUBJECT_CODE} ${s.COURSE_NUMBER} ${s.SECTION_NUMBER} - ${s.TITLE}`,meetings:s.MEETINGS,finalExamDate:s.FINAL_EXAM_STARTDATE,dropDate:s.DROP_DATE,allowedDropDesc:s.ALLOWED_DROP_DESC,description:s.DESCRIPTION})}return{course_list:e,term:r}})();E.exports={courses:$}});var D=u((A,T)=>{var l=class e{#t;#s;#e;#i;#n;#r;static formatICalString(t){return`${t.replace(/\\/g,"\\\\").replace(/;/g,"\\;").replace(/,/g,"\\,").replace(/\n/g,"\\n")}`.match(/.{1,75}/g).map((s,n)=>n===0?s:" "+s).join(`\r
`)}static utcToLocalISOString(t){let r=new Date(t),i=C=>String(C).padStart(2,"0"),s=r.getFullYear(),n=i(r.getMonth()+1),a=i(r.getDate()),f=i(r.getHours()),w=i(r.getMinutes()),I=i(r.getSeconds());return`${s}-${n}-${a}T${f}:${w}:${I}`}static findFirstMatchingWeekday(t,r){let i={MO:1,TU:2,WE:3,TH:4,FR:5},s=r.map(a=>i[a]),n=t;for(;!s.includes(n.getDay());)n.setDate(n.getDate()+1);return n}setTitle(t){if(!t||typeof t!="string")throw new Error("CalendarEventBuilder.setTitle: title must be a non-empty string");return this.#t=e.formatICalString(t),this}setStartTime(t){if(!(t instanceof Date)||isNaN(t))throw new Error("CalendarEventBuilder.setStartTime: startTime must be a valid Date object");return this.#s=t,this}setEndTime(t){if(!(t instanceof Date)||isNaN(t))throw new Error("CalendarEventBuilder.setEndTime: endTime must be a valid Date object");return this.#e=t,this}setLocation(t){if(!t||typeof t!="string")throw new Error("CalendarEventBuilder.setLocation: location must be a non-empty string");return this.#i=e.formatICalString(t),this}setDescription(t){if(!t||typeof t!="string")throw new Error("CalendarEventBuilder.setDescription: description must be a non-empty string");return this.#n=e.formatICalString(t),this}setDays(t){if(!Array.isArray(t)||t.some(r=>typeof r!="string"||r.length!==1))throw new Error("CalendarEventBuilder.setDays: days must be an array of single-character strings");return this.#r=t.map(r=>{switch(r){case"M":return"MO";case"T":return"TU";case"W":return"WE";case"R":return"TH";case"F":return"FR";default:throw new Error(`CalendarEventBuilder.setDays: invalid or non-supported day character '${r}'`)}}),this}build(){let t=new Date(this.#s),r=Intl.DateTimeFormat().resolvedOptions().timeZone;return t.setHours(this.#e.getHours(),this.#e.getMinutes(),this.#e.getSeconds()),["BEGIN:VEVENT",`SUMMARY:${this.#t}`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,"").split(".")[0]}Z`,`UID:${crypto.randomUUID()}`,`${this.#r?`DTSTART;TZID=${r}:${e.utcToLocalISOString(e.findFirstMatchingWeekday(this.#s,this.#r).toISOString()).replace(/[-:]/g,"").split(".")[0]}`:`DTSTART;TZID=${r}:${e.utcToLocalISOString(this.#s).replace(/[-:]/g,"").split(".")[0]}`}`,`DTEND;TZID=${r}:${e.utcToLocalISOString(t.toISOString()).replace(/[-:]/g,"").split(".")[0]}`,`${this.#i?`LOCATION:${this.#i}`:""}`,`DESCRIPTION:${this.#n}`,`${this.#r?`RRULE:FREQ=WEEKLY;BYDAY=${this.#r.join(",")};UNTIL=${this.#e.toISOString().replace(/[-:]/g,"").split(".")[0]}Z`:""}`,"END:VEVENT"].filter(i=>i!=="").join(`\r
`)}},c=class{#t=[];addEvent(t){if(t=t.trim(),console.log(t),typeof t!="string"||!t.startsWith("BEGIN:VEVENT")||!t.endsWith("END:VEVENT"))throw new Error("CalendarBuilder.addEvent: event must be a valid VEVENT string");return this.#t.push(t),this}build(){return["BEGIN:VCALENDAR","VERSION:2.0","CALSCALE:GREGORIAN",...this.#t,"END:VCALENDAR"].filter(t=>t!=="").join(`\r
`)}};T.exports={CalendarEventBuilder:l,CalendarBuilder:c}});var{courses:{course_list:g,term:m}}=h(),{CalendarBuilder:N,CalendarEventBuilder:p}=D();if(!window?.location?.href||!window.location.href.startsWith("https://my.ucdavis.edu/schedulebuilder/"))throw alert("This bookmarklet only works on the UCD Schedule Builder page (https://my.ucdavis.edu/schedulebuilder/)."),new Error("Not on UCD Schedule Builder page");var d=new N;for(let e of g){for(let t of e.meetings)d.addEvent(new p().setTitle(e.title+` (${t.TYPE})`).setStartTime(t.STARTTIME).setEndTime(t.ENDTIME).setLocation(t.LOCATION).setDescription(`Last date to drop: ${e.dropDate.toLocaleString().split(",")[0]}

${e.description}`).setDays(t.WEEKDAYS.split(",")).build());d.addEvent(new p().setTitle(e.title+" (Final Exam)").setStartTime(e.finalExamDate).setEndTime(new Date(e.finalExamDate.getTime()+7200*1e3)).setDescription(`Final Exam for ${e.title}

${e.description}`).build())}var R=d.build(),y=new Blob([R],{type:"text/calendar"}),S=URL.createObjectURL(y),o=document.createElement("a");o.href=S;o.download=`ucd_schedule_${m.replace(" ","_")}.ics`;document.body.appendChild(o);o.click();document.body.removeChild(o);URL.revokeObjectURL(S);console.log(`Exported ${g.length} courses for term ${m}`);})();
})();
