(() => {
(()=>{var u=(e,t)=>()=>(t||e((t={exports:{}}).exports,t),t.exports);var h=u((b,E)=>{if(!window?.location?.href||!window.location.href.startsWith("https://my.ucdavis.edu/schedulebuilder/"))throw alert("This bookmarklet only works on the UCD Schedule Builder page (https://my.ucdavis.edu/schedulebuilder/)."),new Error("Not on UCD Schedule Builder page");var N=(()=>{let e=[],t=schedule.currSched.get(),r=CourseDetails[[Object.keys(CourseDetails)[0]]].COURSE_MATERIALS_TERM;for(let s in t)if(t[s].STORED_REGISTRATION_STATUS==="Registered"){let i=CourseDetails[s];e.push({title:`${i.SUBJECT_CODE} ${i.COURSE_NUMBER} ${i.SECTION_NUMBER} - ${i.TITLE}`,meetings:i.MEETINGS,finalExamDate:i.FINAL_EXAM_STARTDATE,dropDate:i.DROP_DATE,allowedDropDesc:i.ALLOWED_DROP_DESC,description:i.DESCRIPTION})}return{course_list:e,term:r}})();E.exports={courses:N}});var g=u((A,T)=>{var l=class e{#t;#e;#r;#s;#n;#i;static formatICalString(t){return`${t.replace(/\\/g,"\\\\").replace(/;/g,"\\;").replace(/,/g,"\\,").replace(/\n/g,"\\n")}`.match(/.{1,75}/g).map((i,n)=>n===0?i:" "+i).join(`\r
`)}static utcToLocalISOString(t){let r=new Date(t),s=C=>String(C).padStart(2,"0"),i=r.getFullYear(),n=s(r.getMonth()+1),a=s(r.getDate()),f=s(r.getHours()),w=s(r.getMinutes()),I=s(r.getSeconds());return`${i}-${n}-${a}T${f}:${w}:${I}`}static findFirstMatchingWeekday(t,r){let s={MO:1,TU:2,WE:3,TH:4,FR:5},i=r.map(a=>s[a]),n=t;for(;!i.includes(n.getDay());)n.setDate(n.getDate()+1);return n}setTitle(t){if(!t||typeof t!="string")throw new Error("CalendarEventBuilder.setTitle: title must be a non-empty string");return this.#t=e.formatICalString(t),this}setStartTime(t){if(!(t instanceof Date)||isNaN(t))throw new Error("CalendarEventBuilder.setStartTime: startTime must be a valid Date object");return this.#e=t,this}setEndTime(t){if(!(t instanceof Date)||isNaN(t))throw new Error("CalendarEventBuilder.setEndTime: endTime must be a valid Date object");return this.#r=t,this}setLocation(t){if(!t||typeof t!="string")throw new Error("CalendarEventBuilder.setLocation: location must be a non-empty string");return this.#s=e.formatICalString(t),this}setDescription(t){if(!t||typeof t!="string")throw new Error("CalendarEventBuilder.setDescription: description must be a non-empty string");return this.#n=e.formatICalString(t),this}setDays(t){if(!Array.isArray(t)||t.some(r=>typeof r!="string"||r.length!==1))throw new Error("CalendarEventBuilder.setDays: days must be an array of single-character strings");return this.#i=t.map(r=>{switch(r){case"M":return"MO";case"T":return"TU";case"W":return"WE";case"R":return"TH";case"F":return"FR";default:throw new Error(`CalendarEventBuilder.setDays: invalid or non-supported day character '${r}'`)}}),this}build(){this.#i&&(this.#e=e.findFirstMatchingWeekday(this.#e,this.#i));let t=new Date(this.#e),r=Intl.DateTimeFormat().resolvedOptions().timeZone;return t.setHours(this.#r.getHours(),this.#r.getMinutes(),this.#r.getSeconds()),["BEGIN:VEVENT",`SUMMARY:${this.#t}`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,"").split(".")[0]}Z`,`UID:${crypto.randomUUID()}`,`DTSTART;TZID=${r}:${e.utcToLocalISOString(this.#e.toISOString()).replace(/[-:]/g,"").split(".")[0]}`,`DTEND;TZID=${r}:${e.utcToLocalISOString(t.toISOString()).replace(/[-:]/g,"").split(".")[0]}`,`${this.#s?`LOCATION:${this.#s}`:""}`,`DESCRIPTION:${this.#n}`,`${this.#i?`RRULE:FREQ=WEEKLY;BYDAY=${this.#i.join(",")};UNTIL=${e.utcToLocalISOString(this.#r.toISOString()).replace(/[-:]/g,"").split(".")[0]}`:""}`,"END:VEVENT"].filter(s=>s!=="").join(`\r
`)}},c=class{#t=[];addEvent(t){if(t=t.trim(),console.log(t),typeof t!="string"||!t.startsWith("BEGIN:VEVENT")||!t.endsWith("END:VEVENT"))throw new Error("CalendarBuilder.addEvent: event must be a valid VEVENT string");return this.#t.push(t),this}build(){return["BEGIN:VCALENDAR","VERSION:2.0","CALSCALE:GREGORIAN",...this.#t,"END:VCALENDAR"].filter(t=>t!=="").join(`\r
`)}};T.exports={CalendarEventBuilder:l,CalendarBuilder:c}});var{courses:{course_list:p,term:m}}=h(),{CalendarBuilder:R,CalendarEventBuilder:D}=g();if(!window?.location?.href||!window.location.href.startsWith("https://my.ucdavis.edu/schedulebuilder/"))throw alert("This bookmarklet only works on the UCD Schedule Builder page (https://my.ucdavis.edu/schedulebuilder/)."),new Error("Not on UCD Schedule Builder page");var d=new R;for(let e of p){for(let t of e.meetings){if(t.STARTTIME==null||t.ENDTIME==null){console.warn(`Skipping meeting for course ${e.title} due to missing start or end time.`);continue}d.addEvent(new D().setTitle(e.title+` (${t.TYPE})`).setStartTime(t.STARTTIME).setEndTime(t.ENDTIME).setLocation(t.LOCATION).setDescription(`Last date to drop: ${e.dropDate.toLocaleString().split(",")[0]}

${e.description}`).setDays(t.WEEKDAYS.split(",")).build())}e.finalExamDate!=null&&d.addEvent(new D().setTitle(e.title+" (Final Exam)").setStartTime(e.finalExamDate).setEndTime(new Date(e.finalExamDate.getTime()+7200*1e3)).setDescription(`Final Exam for ${e.title}

${e.description}`).build())}var $=d.build(),y=new Blob([$],{type:"text/calendar"}),S=URL.createObjectURL(y),o=document.createElement("a");o.href=S;o.download=`ucd_schedule_${m.replace(" ","_")}.ics`;document.body.appendChild(o);o.click();document.body.removeChild(o);URL.revokeObjectURL(S);console.log(`Exported ${p.length} courses for term ${m}`);})();
})();
